version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-db
    network_mode: "host"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra


volumes:
  cassandra_data:

